# -*- coding: utf-8 -*-
"""Unemployment in india oasis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IfL3wIO9ah2etT3kc8X6iZbPsV6KYAz1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data = pd.read_csv(r"/content/Unemployment in India.csv")

data.head()

data.shape

data.isnull().sum()

data.columns= ["Region","Date","Frequency",
               "Estimated Unemployment Rate",
               "Estimated Employed",
               "Estimated Labour Participation Rate",
               "Area"]

plt.figure(figsize=(12, 10))
sns.heatmap(data.corr())

plt.figure(figsize=(12,8))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Employed", hue="Region", data=data)
plt.show()

plt.figure(figsize=(12, 8))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate", hue="Region", data=data)
plt.show()

